# Generated by Django 3.1.2 on 2021-01-12 05:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('i1', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i2', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i3', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i4', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i5', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i6', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i7', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i8', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i9', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i10', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i1r', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i2r', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i3r', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i4r', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i5r', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i6r', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i7r', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i8r', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i9r', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('i10r', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
