# Generated by Django 3.1.2 on 2021-01-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_drinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, unique=True)),
                ('drinks_per_row', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_id',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ingredient', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pumps',
            fields=[
                ('pump', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ingredient_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ratio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_id', models.IntegerField(unique=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i1',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i10',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i10r',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i1r',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i2',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i2r',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i3',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i3r',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i4',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i4r',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i5',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i5r',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i6',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i6r',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i7',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i7r',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i8',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i8r',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i9',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='i9r',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='img',
        ),
        migrations.AddField(
            model_name='menu',
            name='creator_id',
            field=models.CharField(default='BBC', max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
