# Generated by Django 3.1.5 on 2021-01-23 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210120_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratio',
            name='ingredient_id',
        ),
        migrations.AddField(
            model_name='ratio',
            name='ingredient',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratio',
            name='menu_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
