# Generated by Django 3.1.5 on 2021-01-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210123_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumps',
            name='volume_left',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
