# Generated by Django 3.1.5 on 2021-01-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pumps_volume_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type_id',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
