# Generated by Django 3.1.2 on 2021-02-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_menu_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumps',
            name='ingredient_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
