# Generated by Django 3.1.2 on 2021-02-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210131_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumps',
            name='ingredient_id',
            field=models.CharField(max_length=100),
        ),
    ]
