# Generated by Django 3.1.2 on 2021-02-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210207_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratio',
            name='total_ingredients',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
