# Generated by Django 3.1.7 on 2021-03-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ratio_total_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumps',
            name='pump_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
