# Generated by Django 3.1.7 on 2021-03-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pumps_pump_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumps',
            name='pump_id',
        ),
    ]
