# Generated by Django 3.1.2 on 2021-04-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pumps_pump_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='picture',
            field=models.ImageField(default='../../img/cocktail_PNG173.png', upload_to=''),
        ),
    ]
