# Generated by Django 3.1.2 on 2021-04-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_menu_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(height_field=400, upload_to='../../img/', width_field=400),
        ),
    ]
