# Generated by Django 3.1.2 on 2021-04-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210408_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(default='../../img/cocktail_PNG173.png', height_field=400, upload_to='../../img/', width_field=400),
        ),
    ]
