# Generated by Django 3.2 on 2021-04-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210412_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
