# Generated by Django 3.2.3 on 2021-05-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratio',
            name='total_ingredients',
        ),
        migrations.AddField(
            model_name='ingredient_id',
            name='dtype',
            field=models.CharField(default='a', max_length=2),
        ),
    ]
