# Generated by Django 3.2.3 on 2021-05-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210525_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient_id',
            name='ingredient_id',
        ),
        migrations.AlterField(
            model_name='ingredient_id',
            name='ingredient',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
