# Generated by Django 3.2.3 on 2021-05-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210525_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_id',
            name='pump_picture',
            field=models.ImageField(default='../../img/default.png', height_field='500', upload_to='../../img', width_field='400'),
        ),
    ]
