# Generated by Django 3.2.3 on 2021-05-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_ingredient_id_pump_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_id',
            name='pump_picture',
            field=models.ImageField(default='../../img/default.png', upload_to='../../img'),
        ),
    ]
