# Generated by Django 3.2.3 on 2021-05-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_ingredient_id_pump_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumps',
            name='pump_id',
        ),
    ]
