# Generated by Django 3.2.3 on 2021-05-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_pumps_pump_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratio',
            name='primary_ingredient',
            field=models.CharField(default='f', max_length=5),
        ),
    ]
