# Generated by Django 3.2.3 on 2021-05-25 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_ratio_primary_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratio',
            name='primary_ingredient',
        ),
    ]
