# Generated by Django 3.2.3 on 2021-06-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_ratio_primary_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratio',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
